services:
  - type: web
    name: reinaerd-umbraco
    env: dotnet
    buildCommand: dotnet publish -c Release -o out
    startCommand: dotnet Reinaerd.Umbrico.Site.dll
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
    plan: free
